/**
 * Peculiar Cherubs — Public Cloudflare Worker
 * Stage 4: D1 Public Read API + Content Contract Parity
 */

import { PUBLIC_SECTION_KEYS } from "./contentContract.js";
import {
  loadPublicSections,
  validateRequestedKeys
} from "./publicApi.js";

function json(data, status = 200, extraHeaders = {}) {
  return Response.json(data, {
    status,
    headers: {
      "Cache-Control": "no-store",
      "X-Content-Type-Options": "nosniff",
      "Referrer-Policy": "strict-origin-when-cross-origin",
      ...extraHeaders
    }
  });
}

function errorResponse(error) {
  const status = Number(error?.status || 500);
  const body = {
    ok: false,
    error: String(error?.code || "internal_error")
  };

  if (Array.isArray(error?.invalid)) {
    body.invalid = error.invalid;
  }

  if (status >= 500) {
    console.error("[PublicWorker]", {
      error: body.error,
      name: error?.name || "Error"
    });
  }

  return json(body, status);
}

function runtimeConfig(env) {
  const provider =
    String(env.PUBLIC_PROVIDER || "cloudflare").trim() === "cloudflare"
      ? "cloudflare"
      : "supabase-legacy";

  const payload = {
    publicProvider: provider,
    cloudflare: {
      publicApiBase: "/api/public"
    },
    fetchTimeoutMs: 4000,
    circuitBreakerMs: 60000
  };

  return `/**
 * Generated by the Peculiar Cherubs Public Worker.
 * Provider selection belongs to the deployment environment, not localStorage.
 */
(function (global) {
  "use strict";
  global.PeculiarRuntimeConfig = Object.freeze(${JSON.stringify(payload, null, 2)});
})(typeof window !== "undefined" ? window : globalThis);
`;
}

async function assertDatabaseReady(env) {
  const rows = await env.DB.prepare(`
    SELECT key, value
    FROM schema_meta
    WHERE key IN (
      'application_schema',
      'worship_location_model',
      'public_content_contract',
      'last_import_rehearsal'
    )
  `).all();

  const values = Object.fromEntries(
    (rows.results || []).map(row => [row.key, row.value])
  );

  if (values.application_schema !== "cloudflare-stage-2-v1") {
    const err = new Error("d1_application_schema_missing");
    err.code = "d1_application_schema_missing";
    err.status = 503;
    throw err;
  }

  if (values.worship_location_model !== "peculiar-hq-v1") {
    const err = new Error("d1_worship_location_model_missing");
    err.code = "d1_worship_location_model_missing";
    err.status = 503;
    throw err;
  }

  if (values.public_content_contract !== "cloudflare-stage-4-v1") {
    const err = new Error("d1_public_contract_missing");
    err.code = "d1_public_contract_missing";
    err.status = 503;
    throw err;
  }

  if (!values.last_import_rehearsal) {
    const err = new Error("d1_import_rehearsal_missing");
    err.code = "d1_import_rehearsal_missing";
    err.status = 503;
    throw err;
  }

  return values;
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    try {
      if (url.pathname === "/js/data/runtimeConfig.js") {
        return new Response(runtimeConfig(env), {
          status: 200,
          headers: {
            "Content-Type": "application/javascript; charset=utf-8",
            "Cache-Control": "no-store",
            "X-Content-Type-Options": "nosniff"
          }
        });
      }

      if (
        url.pathname === "/admin" ||
        url.pathname === "/admin/" ||
        url.pathname.startsWith("/admin/")
      ) {
        return json({ ok: false, error: "not_found" }, 404);
      }

      if (url.pathname === "/__health") {
        const schema = await assertDatabaseReady(env);

        return json({
          ok: true,
          service: "peculiar-cherubs-public",
          stage: "cloudflare-stage-4",
          provider: env.PUBLIC_PROVIDER || "cloudflare",
          database_ready: true,
          application_schema: schema.application_schema,
          worship_location_model: schema.worship_location_model,
          public_content_contract: schema.public_content_contract,
          imported_at: schema.last_import_rehearsal
        });
      }

      if (url.pathname === "/api/public/manifest") {
        await assertDatabaseReady(env);

        return json({
          ok: true,
          contract: "peculiar-cherubs-public-v1",
          sections: PUBLIC_SECTION_KEYS
        });
      }

      if (url.pathname === "/api/public/sections") {
        if (request.method !== "GET" && request.method !== "HEAD") {
          return json(
            { ok: false, error: "method_not_allowed" },
            405,
            { Allow: "GET, HEAD" }
          );
        }

        await assertDatabaseReady(env);

        const keys = validateRequestedKeys(url.searchParams.get("keys"));
        const sections = await loadPublicSections(env.DB, keys);

        const response = {
          ok: true,
          contract: "peculiar-cherubs-public-v1",
          sections
        };

        return request.method === "HEAD"
          ? new Response(null, {
              status: 200,
              headers: {
                "Cache-Control": "no-store",
                "X-Content-Type-Options": "nosniff"
              }
            })
          : json(response);
      }

      if (url.pathname.startsWith("/api/public/")) {
        return json({ ok: false, error: "not_found" }, 404);
      }

      return env.ASSETS.fetch(request);
    } catch (error) {
      return errorResponse(error);
    }
  }
};
