begin;
insert into public.cms_permissions(permission_key,label,description) values ('livestream.manage','Broadcasts','Manage multi-chapel live, upcoming and recap broadcasts.') on conflict(permission_key) do update set label=excluded.label,description=excluded.description;
insert into public.cms_role_permissions(role_key,permission_key) values ('super_admin','livestream.manage'),('content_manager','livestream.manage'),('communications_editor','livestream.manage') on conflict do nothing;
create or replace function public.cms_can_write_key(p_key text) returns boolean language plpgsql stable security definer set search_path=public as $$
declare v_permission text;
begin
 if not public.is_cms_admin() then return false; end if;
 if public.cms_has_permission('advanced.manage') then return true; end if;
 v_permission:=case p_key when 'publications' then 'publications.manage' when 'sermons' then 'sermons.manage' when 'events' then 'events.manage' when 'ministries' then 'ministries.manage' when 'chapels' then 'ministries.manage' when 'bibleCollege' then 'ministries.manage' when 'about' then 'about.manage' when 'quickLinks' then 'quicklinks.manage' when 'give' then 'giving.manage' when 'site' then 'site.manage' when 'navigation' then 'site.manage' when 'home' then 'site.manage' when 'livestream' then 'livestream.manage' else null end;
 return v_permission is not null and public.cms_has_permission(v_permission);
end;$$;
revoke all on function public.cms_can_write_key(text) from public; grant execute on function public.cms_can_write_key(text) to authenticated;
insert into public.site_content(key,data) values ('livestream','{"hero":{"eyebrow":"Peculiar Cherubs Live","title":"One church. Many worshipping communities.","description":"Join live services, revisit the latest broadcast, and see what is coming next."},"channels":{"mother-church":{"enabled":true,"label":"Mother Church","statusOverride":"auto","youtubeChannelUrl":"https://youtube.com/@peculiarcherubschurch","currentBroadcast":{"title":"","speaker":"","serviceType":"Sunday Worship","videoUrl":"","startsAt":"","endsAt":""},"schedule":[{"label":"Sunday Worship","dayOfWeek":0,"time":"09:00"}],"utcOffsetMinutes":60},"pdcm-gwarinpa":{"enabled":true,"statusOverride":"auto","youtubeChannelUrl":"","currentBroadcast":{"title":"","speaker":"","serviceType":"Sunday Worship","videoUrl":"","startsAt":"","endsAt":""},"schedule":[{"label":"Sunday Worship","dayOfWeek":0,"time":"09:00"}],"utcOffsetMinutes":60},"pdcm-english":{"enabled":true,"statusOverride":"auto","youtubeChannelUrl":"","currentBroadcast":{"title":"","speaker":"","serviceType":"Sunday Worship","videoUrl":"","startsAt":"","endsAt":""},"schedule":[{"label":"Sunday Worship","dayOfWeek":0,"time":"09:00"}],"utcOffsetMinutes":60},"pdcm-byazhin":{"enabled":true,"statusOverride":"auto","youtubeChannelUrl":"","currentBroadcast":{"title":"","speaker":"","serviceType":"Sunday Worship","videoUrl":"","startsAt":"","endsAt":""},"schedule":[{"label":"Sunday Worship","dayOfWeek":0,"time":"09:00"}],"utcOffsetMinutes":60},"pdcm-mega-youth":{"enabled":true,"statusOverride":"auto","youtubeChannelUrl":"","currentBroadcast":{"title":"","speaker":"","serviceType":"Sunday Worship","videoUrl":"","startsAt":"","endsAt":""},"schedule":[{"label":"Sunday Worship","dayOfWeek":0,"time":"09:00"}],"utcOffsetMinutes":60}}}'::jsonb) on conflict(key) do nothing;
commit;
select key,updated_at from public.site_content where key='livestream';
